### ISSUE TITLE
separate list for bug abusers and hard cheaters

### ISSUE THREAD

**Issue by Frambooisier** [aliakbarazizi/cheaters-coh2#5]
hey,

I think it would be better to create two separate lists for goofy people and hardcore cheaters, you can deal with goofy people but it's really difficult to fight maphackers

**Comment by aliakbarazizi** [comment]
> hey,
> 
> I think it would be better to create two separate lists for goofy people and hardcore cheaters, you can deal with goofy people but it's really difficult to fight maphackers

Since I didn't play that much recently, I didn't notice any new user yet, but I will try to update the list as much as possible

For now you can add your names with proof and I will add them to the list.
